version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.23-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  task_scheduler:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
